config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'posts/new'
  get    'users/new'
  root   'static_pages#home'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
    <footer class="bg-dark py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-8 text-center text-md-left mb-3 mb-md-0">
            <small class="text-white">&copy; 2020 <a class="text-white" href="#">zimotoai</a>. All Rights Reserved.</small>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
 <header role="header">
  <nav class="js-navbar-scroll navbar fixed-top navbar-expand-lg navbar-dark" style="background-color :rgba(98, 42, 136, 0.7); width:100%;">
    <div class="container-fluid">
          <div class="navbar-brand">
            <%= link_to root_path do %>
              <%= image_tag 'zimotoai.png', size: "280x60", alt: "地元あい", class: "none" %>
            <% end %>
          </div>

      <button class="navbar-toggler" type="button"
        data-toggle="collapse"
        data-target="#navbarTogglerDemo"

        aria-controls="navbarTogglerDemo"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo" aria-hidden="true">
        <ul class="navbar-nav ml-auto mt-0">
          <li class="nav-item mr-4 mb-0">
            <%= link_to 'ホーム', root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item mr-4 mb-0">
            <%= link_to 'サービス紹介', about_path, class: "nav-link active"  %>
          </li>
          <li class="nav-item mr-4 mb-0">
            <%= link_to '思い出シェア', contact_path, class: "nav-link active"  %>
          </li>
          <% if logged_in? %>
            <li class="nav-item mr-4 mb-0">
            <%= link_to '私の思い出', current_user, class: "nav-link active"  %>
            </li>
            <%=button_to 'ログアウト', "/logout", method: :delete, class: "btn btn-primary" %>
          <% else %>
          <li class="nav-item mr-4 mb-0">
            <%= link_to '無料登録', signup_path, class: "nav-link active"  %>
          </li>
            <%=link_to 'ログイン', login_path, class: "btn btn-primary" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
  <title><%= full_title(yield(:title)) %></title>    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="サービス紹介から抜粋">
    <meta name="author" content="Kanou Shimon">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link href="//fonts.googleapis.com/css?family=Playfair+Display:400,700%7COpen+Sans:300,400,600,700" rel="stylesheet">
    <!--<link rel="stylesheet" type="text/css" href="assets/vendors/bootstrap/css/bootstrap.css">-->
    <!--<link rel="stylesheet" type="text/css" href="assets/vendors/font-awesome/css/fontawesome-all.min.css">-->
    <!--<link rel="stylesheet" type="text/css" href="assets/vendors/magnific-popup/magnific-popup.css">-->
    <!--<link rel="stylesheet" type="text/scss" href="app/assets/stylesheets/mystyles.scss">-->
    
    
  
    <%= render 'layouts/shim' %>
  </head>
    
  <body>
    <%= render 'layouts/header'%>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>

  <!-- JAVASCRIPTS (Load javascripts at bottom, this will reduce page load time) -->
    <!-- Global Vendor -->
    <script src="assets/vendors/jquery.min.js"></script>
    <script src="assets/vendors/jquery.migrate.min.js"></script>
    <script src="assets/vendors/popper.min.js"></script>
    <script src="assets/vendors/bootstrap/js/bootstrap.min.js"></script>

    <!-- Components Vendor  -->
    <script src="assets/vendors/jquery.parallax.js"></script>
    <script src="assets/vendors/magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="assets/vendors/shuffle/jquery.shuffle.min.js"></script>

    <!-- Theme Settings and Calls -->
    <script src="assets/js/myglobal.js"></script>

    <!-- Theme Components and Settings -->
    <script src="assets/js/vendors/parallax.js"></script>
    <script src="assets/js/vendors/magnific-popup.js"></script>
    <script src="assets/js/vendors/shuffle.js"></script>
    
    <!--<script src="app/assets/javascripts/modal.js"></script>-->
    <script>
    $('.js-modal-open').on('click', function(){
      var target = $(this).data('target');
      var modal = document.getElementById(target);
      scrollPosition = $(window).scrollTop();
    
      $('body').addClass('fixed').css({'top': -scrollPosition});
      $(modal).fadeIn();
      return false;
    });
    
    $('.js-modal-close').on('click', function(){
      $('body').removeClass('fixed');
      window.scrollTo( 0 , scrollPosition );
      $('.js-modal').fadeOut();
      return false;
    });
    </script>
    
    <!-- END JAVASCRIPTS -->
    
  </body>
</html>